/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sonic.sync.core.libtorrent.swig;

public class alert {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected alert(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(alert obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_alert(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int type() {
    return libtorrent_jni.alert_type(swigCPtr, this);
  }

  public String what() {
    return libtorrent_jni.alert_what(swigCPtr, this);
  }

  public String message() {
    return libtorrent_jni.alert_message(swigCPtr, this);
  }

  public alert_category_t category() {
    return new alert_category_t(libtorrent_jni.alert_category(swigCPtr, this), true);
  }

  public static SWIGTYPE_p_libtorrent__torrent_removed_alert cast_to_torrent_removed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_torrent_removed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__torrent_removed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__read_piece_alert cast_to_read_piece_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_read_piece_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__read_piece_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__file_completed_alert cast_to_file_completed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_file_completed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__file_completed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__file_renamed_alert cast_to_file_renamed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_file_renamed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__file_renamed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__file_rename_failed_alert cast_to_file_rename_failed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_file_rename_failed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__file_rename_failed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__performance_alert cast_to_performance_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_performance_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__performance_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__state_changed_alert cast_to_state_changed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_state_changed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__state_changed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__tracker_error_alert cast_to_tracker_error_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_tracker_error_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__tracker_error_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__tracker_warning_alert cast_to_tracker_warning_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_tracker_warning_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__tracker_warning_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__scrape_reply_alert cast_to_scrape_reply_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_scrape_reply_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__scrape_reply_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__scrape_failed_alert cast_to_scrape_failed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_scrape_failed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__scrape_failed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__tracker_reply_alert cast_to_tracker_reply_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_tracker_reply_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__tracker_reply_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_reply_alert cast_to_dht_reply_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_reply_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_reply_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__tracker_announce_alert cast_to_tracker_announce_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_tracker_announce_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__tracker_announce_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__hash_failed_alert cast_to_hash_failed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_hash_failed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__hash_failed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__peer_ban_alert cast_to_peer_ban_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_peer_ban_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__peer_ban_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__peer_unsnubbed_alert cast_to_peer_unsnubbed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_peer_unsnubbed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__peer_unsnubbed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__peer_snubbed_alert cast_to_peer_snubbed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_peer_snubbed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__peer_snubbed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__peer_error_alert cast_to_peer_error_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_peer_error_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__peer_error_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__peer_connect_alert cast_to_peer_connect_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_peer_connect_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__peer_connect_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__peer_disconnected_alert cast_to_peer_disconnected_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_peer_disconnected_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__peer_disconnected_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__invalid_request_alert cast_to_invalid_request_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_invalid_request_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__invalid_request_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__torrent_finished_alert cast_to_torrent_finished_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_torrent_finished_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__torrent_finished_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__piece_finished_alert cast_to_piece_finished_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_piece_finished_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__piece_finished_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__request_dropped_alert cast_to_request_dropped_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_request_dropped_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__request_dropped_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__block_timeout_alert cast_to_block_timeout_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_block_timeout_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__block_timeout_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__block_finished_alert cast_to_block_finished_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_block_finished_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__block_finished_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__block_downloading_alert cast_to_block_downloading_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_block_downloading_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__block_downloading_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__unwanted_block_alert cast_to_unwanted_block_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_unwanted_block_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__unwanted_block_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__storage_moved_alert cast_to_storage_moved_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_storage_moved_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__storage_moved_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__storage_moved_failed_alert cast_to_storage_moved_failed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_storage_moved_failed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__storage_moved_failed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__torrent_deleted_alert cast_to_torrent_deleted_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_torrent_deleted_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__torrent_deleted_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__torrent_delete_failed_alert cast_to_torrent_delete_failed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_torrent_delete_failed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__torrent_delete_failed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__save_resume_data_alert cast_to_save_resume_data_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_save_resume_data_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__save_resume_data_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__save_resume_data_failed_alert cast_to_save_resume_data_failed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_save_resume_data_failed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__save_resume_data_failed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__torrent_paused_alert cast_to_torrent_paused_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_torrent_paused_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__torrent_paused_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__torrent_resumed_alert cast_to_torrent_resumed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_torrent_resumed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__torrent_resumed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__torrent_checked_alert cast_to_torrent_checked_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_torrent_checked_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__torrent_checked_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__url_seed_alert cast_to_url_seed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_url_seed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__url_seed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__file_error_alert cast_to_file_error_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_file_error_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__file_error_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__metadata_failed_alert cast_to_metadata_failed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_metadata_failed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__metadata_failed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__metadata_received_alert cast_to_metadata_received_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_metadata_received_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__metadata_received_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__udp_error_alert cast_to_udp_error_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_udp_error_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__udp_error_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__external_ip_alert cast_to_external_ip_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_external_ip_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__external_ip_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__listen_failed_alert cast_to_listen_failed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_listen_failed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__listen_failed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__listen_succeeded_alert cast_to_listen_succeeded_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_listen_succeeded_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__listen_succeeded_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__portmap_error_alert cast_to_portmap_error_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_portmap_error_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__portmap_error_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__portmap_alert cast_to_portmap_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_portmap_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__portmap_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__portmap_log_alert cast_to_portmap_log_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_portmap_log_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__portmap_log_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__fastresume_rejected_alert cast_to_fastresume_rejected_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_fastresume_rejected_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__fastresume_rejected_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__peer_blocked_alert cast_to_peer_blocked_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_peer_blocked_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__peer_blocked_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_announce_alert cast_to_dht_announce_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_announce_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_announce_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_get_peers_alert cast_to_dht_get_peers_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_get_peers_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_get_peers_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__stats_alert cast_to_stats_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_stats_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__stats_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__cache_flushed_alert cast_to_cache_flushed_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_cache_flushed_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__cache_flushed_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__anonymous_mode_alert cast_to_anonymous_mode_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_anonymous_mode_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__anonymous_mode_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__lsd_peer_alert cast_to_lsd_peer_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_lsd_peer_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__lsd_peer_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__trackerid_alert cast_to_trackerid_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_trackerid_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__trackerid_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_bootstrap_alert cast_to_dht_bootstrap_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_bootstrap_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_bootstrap_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__torrent_error_alert cast_to_torrent_error_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_torrent_error_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__torrent_error_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__torrent_need_cert_alert cast_to_torrent_need_cert_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_torrent_need_cert_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__torrent_need_cert_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__incoming_connection_alert cast_to_incoming_connection_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_incoming_connection_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__incoming_connection_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__add_torrent_alert cast_to_add_torrent_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_add_torrent_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__add_torrent_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__state_update_alert cast_to_state_update_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_state_update_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__state_update_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__session_stats_alert cast_to_session_stats_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_session_stats_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__session_stats_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_error_alert cast_to_dht_error_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_error_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_error_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_immutable_item_alert cast_to_dht_immutable_item_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_immutable_item_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_immutable_item_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_mutable_item_alert cast_to_dht_mutable_item_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_mutable_item_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_mutable_item_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_put_alert cast_to_dht_put_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_put_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_put_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__i2p_alert cast_to_i2p_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_i2p_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__i2p_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_outgoing_get_peers_alert cast_to_dht_outgoing_get_peers_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_outgoing_get_peers_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_outgoing_get_peers_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__log_alert cast_to_log_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_log_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__log_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__torrent_log_alert cast_to_torrent_log_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_torrent_log_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__torrent_log_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__peer_log_alert cast_to_peer_log_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_peer_log_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__peer_log_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__lsd_error_alert cast_to_lsd_error_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_lsd_error_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__lsd_error_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_stats_alert cast_to_dht_stats_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_stats_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_stats_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__incoming_request_alert cast_to_incoming_request_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_incoming_request_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__incoming_request_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_log_alert cast_to_dht_log_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_log_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_log_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_pkt_alert cast_to_dht_pkt_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_pkt_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_pkt_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_get_peers_reply_alert cast_to_dht_get_peers_reply_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_get_peers_reply_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_get_peers_reply_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_direct_response_alert cast_to_dht_direct_response_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_direct_response_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_direct_response_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__picker_log_alert cast_to_picker_log_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_picker_log_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__picker_log_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__session_error_alert cast_to_session_error_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_session_error_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__session_error_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_live_nodes_alert cast_to_dht_live_nodes_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_live_nodes_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_live_nodes_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__session_stats_header_alert cast_to_session_stats_header_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_session_stats_header_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__session_stats_header_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__dht_sample_infohashes_alert cast_to_dht_sample_infohashes_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_dht_sample_infohashes_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__dht_sample_infohashes_alert(cPtr, false);
  }

  public static SWIGTYPE_p_libtorrent__block_uploaded_alert cast_to_block_uploaded_alert(alert a) {
    long cPtr = libtorrent_jni.alert_cast_to_block_uploaded_alert(alert.getCPtr(a), a);
    return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__block_uploaded_alert(cPtr, false);
  }

  public long get_timestamp() {
    return libtorrent_jni.alert_get_timestamp(swigCPtr, this);
  }

  public final static alert_category_t error_notification = new alert_category_t(libtorrent_jni.alert_error_notification_get(), false);
  public final static alert_category_t peer_notification = new alert_category_t(libtorrent_jni.alert_peer_notification_get(), false);
  public final static alert_category_t port_mapping_notification = new alert_category_t(libtorrent_jni.alert_port_mapping_notification_get(), false);
  public final static alert_category_t storage_notification = new alert_category_t(libtorrent_jni.alert_storage_notification_get(), false);
  public final static alert_category_t tracker_notification = new alert_category_t(libtorrent_jni.alert_tracker_notification_get(), false);
  public final static alert_category_t debug_notification = new alert_category_t(libtorrent_jni.alert_debug_notification_get(), false);
  public final static alert_category_t status_notification = new alert_category_t(libtorrent_jni.alert_status_notification_get(), false);
  public final static alert_category_t progress_notification = new alert_category_t(libtorrent_jni.alert_progress_notification_get(), false);
  public final static alert_category_t ip_block_notification = new alert_category_t(libtorrent_jni.alert_ip_block_notification_get(), false);
  public final static alert_category_t performance_warning = new alert_category_t(libtorrent_jni.alert_performance_warning_get(), false);
  public final static alert_category_t dht_notification = new alert_category_t(libtorrent_jni.alert_dht_notification_get(), false);
  public final static alert_category_t stats_notification = new alert_category_t(libtorrent_jni.alert_stats_notification_get(), false);
  public final static alert_category_t session_log_notification = new alert_category_t(libtorrent_jni.alert_session_log_notification_get(), false);
  public final static alert_category_t torrent_log_notification = new alert_category_t(libtorrent_jni.alert_torrent_log_notification_get(), false);
  public final static alert_category_t peer_log_notification = new alert_category_t(libtorrent_jni.alert_peer_log_notification_get(), false);
  public final static alert_category_t incoming_request_notification = new alert_category_t(libtorrent_jni.alert_incoming_request_notification_get(), false);
  public final static alert_category_t dht_log_notification = new alert_category_t(libtorrent_jni.alert_dht_log_notification_get(), false);
  public final static alert_category_t dht_operation_notification = new alert_category_t(libtorrent_jni.alert_dht_operation_notification_get(), false);
  public final static alert_category_t port_mapping_log_notification = new alert_category_t(libtorrent_jni.alert_port_mapping_log_notification_get(), false);
  public final static alert_category_t picker_log_notification = new alert_category_t(libtorrent_jni.alert_picker_log_notification_get(), false);
  public final static alert_category_t all_categories = new alert_category_t(libtorrent_jni.alert_all_categories_get(), false);
}
